### ISSUE TITLE
feature request: render with template

### ISSUE THREAD

**Issue by cospotato** [theme-next/theme-next-gitment#2]
## Example

```yaml
exif:
  enable: true
  template: 'with {Model} {FocalLength}mm f/{FNumber} {ExposureTime}s'
```

render to

```
with ILCE-7RM2 50mm f/1.8 1/100s
```
